AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true
